spring:
  profiles:
    active: develop
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name:
    url:
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: true

logging:
  level: INFO